import { describe, expect, it } from 'bun:test'
import { RRule } from 'rrule'
import type { CalendarEvent } from '@/components/types'
import dayjs from '@/lib/configs/dayjs-config'
import {
	deleteRecurringEvent,
	generateRecurringEvents,
	updateRecurringEvent as updateRecurringEventImpl,
} from './recurrence-handler'

const updateRecurringEvent = (
	...args: Parameters<typeof updateRecurringEventImpl>
) => updateRecurringEventImpl(...args).events

const createBaseRecurringEvent = (
	overrides: Partial<CalendarEvent> = {}
): CalendarEvent => ({
	id: 'event-1',
	title: 'Weekly Sync',
	start: dayjs('2025-01-06T10:00:00.000Z'),
	end: dayjs('2025-01-06T11:00:00.000Z'),
	rrule: {
		freq: RRule.WEEKLY,
		interval: 1,
		dtstart: new Date('2025-01-06T10:00:00.000Z'),
	},
	...overrides,
})

describe('recurrence-handler utility tests', () => {
	describe('deleteRecurringEvent', () => {
		it('should delete entire series (scope: all) when uid is missing from base event', () => {
			const baseEvent = createBaseRecurringEvent({ id: 'series-1' })
			// Instance generated by the engine would have a generated UID
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-1_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				uid: 'series-1@ilamy.calendar',
				rrule: undefined,
			}

			const currentEvents = [baseEvent]
			const result = deleteRecurringEvent({
				targetEvent: targetInstance,
				currentEvents,
				scope: 'all',
			})

			expect(result.events).toHaveLength(0)
			expect(result.updatedRecurringEvent).toBeUndefined()
			expect(result.deletedEvents?.map((event) => event.id)).toEqual([
				'series-1',
			])
			expect(result.deletedEvents?.[0].uid).toBe('series-1@ilamy.calendar')
		})

		it('should delete entire series (scope: all) when uid is explicitly set', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'series-2',
				uid: 'custom-uid',
			})
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-2_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				uid: 'custom-uid',
				rrule: undefined,
			}

			const currentEvents = [baseEvent]
			const result = deleteRecurringEvent({
				targetEvent: targetInstance,
				currentEvents,
				scope: 'all',
			})

			expect(result.events).toHaveLength(0)
			expect(result.updatedRecurringEvent).toBeUndefined()
			expect(result.deletedEvents?.map((event) => event.id)).toEqual([
				'series-2',
			])
			expect(result.deletedEvents?.[0].uid).toBe('custom-uid')
		})

		it('should remove all series rows from state but only return base for scope all delete callback', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'series-with-override',
				uid: 'custom-uid',
			})
			const overrideEvent: CalendarEvent = {
				...baseEvent,
				id: 'series-with-override_modified',
				start: baseEvent.start.add(1, 'week').add(1, 'hour'),
				end: baseEvent.end.add(1, 'week').add(1, 'hour'),
				recurrenceId: baseEvent.start.add(1, 'week').toISOString(),
				rrule: undefined,
			}
			const otherEvent = createBaseRecurringEvent({
				id: 'other-series',
				uid: 'other-uid',
			})
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-with-override_0',
				rrule: undefined,
			}

			const result = deleteRecurringEvent({
				targetEvent: targetInstance,
				currentEvents: [baseEvent, overrideEvent, otherEvent],
				scope: 'all',
			})

			expect(result.events).toHaveLength(1)
			expect(result.events[0].id).toBe('other-series')
			expect(result.deletedEvents).toHaveLength(1)
			expect(result.deletedEvents?.[0].id).toBe('series-with-override')
			expect(result.deletedEvents?.[0].uid).toBe('custom-uid')
		})

		it('should only delete this instance (scope: this) and update exdates', () => {
			const baseEvent = createBaseRecurringEvent({ id: 'series-3' })
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-3_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				uid: 'series-3@ilamy.calendar',
				rrule: undefined,
			}

			const currentEvents = [baseEvent]
			const result = deleteRecurringEvent({
				targetEvent: targetInstance,
				currentEvents,
				scope: 'this',
			})

			expect(result.events).toHaveLength(1)
			expect(result.events[0].exdates).toContain(
				targetInstance.start.toISOString()
			)
			expect(result.updatedRecurringEvent?.id).toBe('series-3')
			expect(result.updatedRecurringEvent?.exdates).toContain(
				targetInstance.start.toISOString()
			)
			expect(result.deletedEvents).toBeUndefined()
		})

		it('should remove stored override without changing base EXDATEs when scope this targets detached override', () => {
			const occurrenceISO = '2025-01-13T10:00:00.000Z'
			const baseEvent = createBaseRecurringEvent({
				id: 'series-override-delete',
				uid: 'series-override-delete@ilamy.calendar',
				exdates: [occurrenceISO],
			})
			const overrideEvent: CalendarEvent = {
				...baseEvent,
				id: 'series-override-delete_modified',
				start: baseEvent.start.add(1, 'week').add(1, 'hour'),
				end: baseEvent.end.add(1, 'week').add(1, 'hour'),
				recurrenceId: occurrenceISO,
				rrule: undefined,
			}

			const result = deleteRecurringEvent({
				targetEvent: overrideEvent,
				currentEvents: [baseEvent, overrideEvent],
				scope: 'this',
			})

			expect(result.events).toHaveLength(1)
			expect(result.events[0].id).toBe('series-override-delete')
			expect(result.events[0].exdates).toEqual([occurrenceISO])
			expect(result.deletedEvents?.map((event) => event.id)).toEqual([
				'series-override-delete_modified',
			])
			expect(result.updatedRecurringEvent).toBeUndefined()
		})
	})

	describe('updateRecurringEvent', () => {
		it('should update entire series (scope: all) when uid is missing', () => {
			const baseEvent = createBaseRecurringEvent({ id: 'series-4' })
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'series-4_1',
				start: baseEvent.start.add(1, 'week'),
				end: baseEvent.end.add(1, 'week'),
				uid: 'series-4@ilamy.calendar',
				rrule: undefined,
			}

			const currentEvents = [baseEvent]
			const result = updateRecurringEvent({
				targetEvent: targetInstance,
				updates: { title: 'New Title' },
				currentEvents,
				scope: 'all',
			})

			expect(result).toHaveLength(1)
			expect(result[0].title).toBe('New Title')
		})

		it('should remove all detached overrides and keep only the base for scope all from a detached target', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'series-detached',
				uid: 'series-detached@ilamy.calendar',
				start: dayjs('2025-01-06T09:00:00.000Z'),
				end: dayjs('2025-01-06T10:00:00.000Z'),
				exdates: ['2025-01-08T09:00:00.000Z', '2025-01-09T09:00:00.000Z'],
				rrule: {
					freq: RRule.DAILY,
					interval: 1,
					dtstart: new Date('2025-01-06T09:00:00.000Z'),
				},
			})
			const draggedOverride: CalendarEvent = {
				...baseEvent,
				id: 'dragged-override',
				title: 'Dragged override',
				start: dayjs('2025-01-08T15:00:00.000Z'),
				end: dayjs('2025-01-08T16:00:00.000Z'),
				recurrenceId: '2025-01-08T09:00:00.000Z',
				rrule: undefined,
			}
			const otherOverride: CalendarEvent = {
				...baseEvent,
				id: 'other-override',
				title: 'Other override',
				start: dayjs('2025-01-09T12:00:00.000Z'),
				end: dayjs('2025-01-09T13:00:00.000Z'),
				recurrenceId: '2025-01-09T09:00:00.000Z',
				rrule: undefined,
			}

			const result = updateRecurringEvent({
				targetEvent: draggedOverride,
				updates: {
					start: dayjs('2025-01-08T11:00:00.000Z'),
					end: dayjs('2025-01-08T12:00:00.000Z'),
				},
				currentEvents: [baseEvent, draggedOverride, otherOverride],
				scope: 'all',
			})

			expect(result).toHaveLength(1)

			const updatedBase = result[0]
			expect(updatedBase.id).toBe(baseEvent.id)
			expect(updatedBase.rrule).toBeDefined()
			expect(updatedBase.start.toISOString()).toBe('2025-01-06T11:00:00.000Z')
			expect(updatedBase.end.toISOString()).toBe('2025-01-06T12:00:00.000Z')
			expect(updatedBase.exdates).toBeUndefined()
		})

		it('should remove detached overrides and apply submitted time when scope all from a dragged generated instance', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'daily-x',
				uid: 'daily-x@ilamy.calendar',
				start: dayjs('2025-01-06T09:00:00.000Z'),
				end: dayjs('2025-01-06T10:00:00.000Z'),
				exdates: ['2025-01-08T09:00:00.000Z', '2025-01-10T09:00:00.000Z'],
				rrule: {
					freq: RRule.DAILY,
					interval: 1,
					dtstart: new Date('2025-01-06T09:00:00.000Z'),
				},
			})
			const override: CalendarEvent = {
				...baseEvent,
				id: 'daily-x-override',
				title: 'Override',
				start: dayjs('2025-01-08T12:00:00.000Z'),
				end: dayjs('2025-01-08T13:00:00.000Z'),
				recurrenceId: '2025-01-08T09:00:00.000Z',
				rrule: undefined,
			}
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'daily-x_3',
				start: dayjs('2025-01-09T09:00:00.000Z'),
				end: dayjs('2025-01-09T10:00:00.000Z'),
				uid: baseEvent.uid,
				rrule: undefined,
			}

			const result = updateRecurringEvent({
				targetEvent: targetInstance,
				updates: {
					start: dayjs('2025-01-10T12:00:00.000Z'),
					end: dayjs('2025-01-10T13:00:00.000Z'),
				},
				currentEvents: [baseEvent, override],
				scope: 'all',
			})

			expect(result).toHaveLength(1)
			expect(result[0].id).toBe(baseEvent.id)
			expect(result[0].start.toISOString()).toBe('2025-01-06T12:00:00.000Z')
			expect(result[0].end.toISOString()).toBe('2025-01-06T13:00:00.000Z')
			expect(result[0].exdates).toBeUndefined()
		})

		it('should remove detached overrides when scope all has no time changes', () => {
			const baseEvent = createBaseRecurringEvent({
				id: 'daily-title',
				uid: 'daily-title@ilamy.calendar',
				start: dayjs('2025-01-06T09:00:00.000Z'),
				end: dayjs('2025-01-06T10:00:00.000Z'),
				exdates: ['2025-01-08T09:00:00.000Z'],
				rrule: {
					freq: RRule.DAILY,
					interval: 1,
					dtstart: new Date('2025-01-06T09:00:00.000Z'),
				},
			})
			const override: CalendarEvent = {
				...baseEvent,
				id: 'daily-title-override',
				title: 'Override',
				start: dayjs('2025-01-08T12:00:00.000Z'),
				end: dayjs('2025-01-08T13:00:00.000Z'),
				recurrenceId: '2025-01-08T09:00:00.000Z',
				rrule: undefined,
			}
			const targetInstance: CalendarEvent = {
				...baseEvent,
				id: 'daily-title_3',
				start: dayjs('2025-01-09T09:00:00.000Z'),
				end: dayjs('2025-01-09T10:00:00.000Z'),
				uid: baseEvent.uid,
				rrule: undefined,
			}

			const result = updateRecurringEvent({
				targetEvent: targetInstance,
				updates: { title: 'All title' },
				currentEvents: [baseEvent, override],
				scope: 'all',
			})

			expect(result).toHaveLength(1)
			expect(result[0].id).toBe(baseEvent.id)
			expect(result[0].title).toBe('All title')
			expect(result[0].start.toISOString()).toBe(baseEvent.start.toISOString())
			expect(result[0].end.toISOString()).toBe(baseEvent.end.toISOString())
			expect(result[0].exdates).toBeUndefined()
		})
	})

	describe('generateRecurringEvents', () => {
		it('should respect overrides when uid is missing from base but present in override', () => {
			const baseEvent = createBaseRecurringEvent({ id: 'series-5' })
			const overrideDate = baseEvent.start.add(1, 'week')
			const overrideEvent: CalendarEvent = {
				...baseEvent,
				id: 'series-5_override',
				start: overrideDate,
				end: overrideDate.add(1, 'hour'),
				title: 'Overridden Title',
				uid: 'series-5@ilamy.calendar',
				recurrenceId: overrideDate.toISOString(),
			}

			const currentEvents = [baseEvent, overrideEvent]
			const generated = generateRecurringEvents({
				event: baseEvent,
				currentEvents,
				startDate: baseEvent.start.subtract(1, 'day'),
				endDate: baseEvent.start.add(1, 'month'),
			})

			const overridden = generated.find((e) => e.start.isSame(overrideDate))
			expect(overridden?.title).toBe('Overridden Title')
		})
	})
})
